EduHome/Models/BlogBanner.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EduHome.Models
{
    public class BlogBanner
    {
        public int Id { get; set; }
        public string Title { get; set; }
        [Required]
        public string Image { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime? TimeDeleted { get; set; }
    }
}

EduHome/Areas/Admin/Controllers/BlogBannerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EduHome.DAL;
using EduHome.Models;
using Microsoft.AspNetCore.Authorization;

namespace EduHome.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class BlogBannerController : Controller
    {
        private readonly AppDbContext _context;

        public BlogBannerController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Admin/BlogBanner
        public async Task<IActionResult> Index()
        {
            return View(await _context.BlogBanners.ToListAsync());
        }

        // GET: Admin/BlogBanner/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogBanner = await _context.BlogBanners
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blogBanner == null)
            {
                return NotFound();
            }

            return View(blogBanner);
        }

        // GET: Admin/BlogBanner/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/BlogBanner/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Image,IsDeleted,TimeDeleted")] BlogBanner blogBanner)
        {
            if (ModelState.IsValid)
            {
                _context.Add(blogBanner);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(blogBanner);
        }

        // GET: Admin/BlogBanner/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogBanner = await _context.BlogBanners.FindAsync(id);
            if (blogBanner == null)
            {
                return NotFound();
            }
            return View(blogBanner);
        }

        // POST: Admin/BlogBanner/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Image,IsDeleted,TimeDeleted")] BlogBanner blogBanner)
        {
            if (id != blogBanner.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(blogBanner);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogBannerExists(blogBanner.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(blogBanner);
        }

        // GET: Admin/BlogBanner/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogBanner = await _context.BlogBanners
                .FirstOrDefaultAsync(m => m.Id == id);
            if (blogBanner == null)
            {
                return NotFound();
            }

            return View(blogBanner);
        }

        // POST: Admin/BlogBanner/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blogBanner = await _context.BlogBanners.FindAsync(id);
            _context.BlogBanners.Remove(blogBanner);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlogBannerExists(int id)
        {
            return _context.BlogBanners.Any(e => e.Id == id);
        }
    }
}

EduHome/Areas/Admin/Views/BlogBanner/Create.cshtml
@model EduHome.Models.BlogBanner

@{
    ViewData["Title"] = "Create";
}

<h2 style="margin-bottom:20px">Create</h2>

<h4>BlogBanner</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="TimeDeleted" class="control-label"></label>
                <input asp-for="TimeDeleted" class="form-control" />
                <span asp-validation-for="TimeDeleted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

EduHome/Areas/Admin/Views/BlogBanner/Delete.cshtml
@model EduHome.Models.BlogBanner

@{
    ViewData["Title"] = "Delete";
}

<h2 style="margin-bottom:20px">Delete</h2>

<h3 class="text-danger" style="margin-bottom:15px">Are you sure you want to delete this?</h3>
<div>
    <h4>BlogBanner</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.Raw(Model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd>
            <img src="~/img/blog/@Model.Image" style="width:210px!important; height:170px!important;" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TimeDeleted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TimeDeleted)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </form>
</div>

EduHome/Areas/Admin/Views/BlogBanner/Details.cshtml
@model EduHome.Models.BlogBanner

@{
    ViewData["Title"] = "Details";
}

<h2 style="margin-bottom:20px">Details</h2>

<div>
    <h4>BlogBanner</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.Raw(Model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd>
            <img src="~/img/blog/@Model.Image" style="width:210px!important; height:170px!important;" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TimeDeleted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TimeDeleted)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-secondary" style="margin-top:20px" asp-action="Index">Back to List</a>
</div>

EduHome/Areas/Admin/Views/BlogBanner/Edit.cshtml
@model EduHome.Models.BlogBanner

@{
    ViewData["Title"] = "Edit";
}

<h2 style="margin-bottom:20px">Edit</h2>

<h4>BlogBanner</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="TimeDeleted" class="control-label"></label>
                <input asp-for="TimeDeleted" class="form-control" />
                <span asp-validation-for="TimeDeleted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

EduHome/Areas/Admin/Views/BlogBanner/Index.cshtml
@model IEnumerable<EduHome.Models.BlogBanner>

@{
    ViewData["Title"] = "Index";
}

<h4 style="margin-bottom:30px">Blog Banner</h4>

<p>
    <a class="btn btn-success" style="margin-bottom:30px" asp-controller="BlogBanner" asp-action="Create">Create</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsDeleted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TimeDeleted)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.Raw(item.Title)
                </td>
                <td>
                    <img src="~/img/blog/@item.Image" style="width:95px!important; height:92px!important;" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsDeleted)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TimeDeleted)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-secondary"><i class="mdi mdi-information"></i></a>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning"><i class="mdi mdi-update"></i></a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger"><i class="mdi mdi-delete"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>