EduHome/Models/UpcomingEvent.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EduHome.Models
{
    public class UpcomingEvent  
    {
        public int Id { get; set; }
        [Required, StringLength(70)]
        public string Title { get; set; }
        [Required]
        public string Day { get; set; }
        [Required]
        public string TimeSpan { get; set; }
        [Required]
        public string Location { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime? TimeDeleted { get; set; }
    }
}

EduHome/Areas/Admin/Controllers/UpcomingEventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EduHome.DAL;
using EduHome.Models;
using Microsoft.AspNetCore.Authorization;

namespace EduHome.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class UpcomingEventsController : Controller
    {
        private readonly AppDbContext _context;

        public UpcomingEventsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Admin/UpcomingEvents
        public async Task<IActionResult> Index()
        {
            return View(await _context.UpcomingEvents.ToListAsync());
        }

        // GET: Admin/UpcomingEvents/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var upcomingEvent = await _context.UpcomingEvents
                .FirstOrDefaultAsync(m => m.Id == id);
            if (upcomingEvent == null)
            {
                return NotFound();
            }

            return View(upcomingEvent);
        }

        // GET: Admin/UpcomingEvents/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/UpcomingEvents/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Day,TimeSpan,Location,IsDeleted,TimeDeleted")] UpcomingEvent upcomingEvent)
        {
            if (ModelState.IsValid)
            {
                _context.Add(upcomingEvent);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(upcomingEvent);
        }

        // GET: Admin/UpcomingEvents/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var upcomingEvent = await _context.UpcomingEvents.FindAsync(id);
            if (upcomingEvent == null)
            {
                return NotFound();
            }
            return View(upcomingEvent);
        }

        // POST: Admin/UpcomingEvents/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Day,TimeSpan,Location,IsDeleted,TimeDeleted")] UpcomingEvent upcomingEvent)
        {
            if (id != upcomingEvent.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(upcomingEvent);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UpcomingEventExists(upcomingEvent.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(upcomingEvent);
        }

        // GET: Admin/UpcomingEvents/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var upcomingEvent = await _context.UpcomingEvents
                .FirstOrDefaultAsync(m => m.Id == id);
            if (upcomingEvent == null)
            {
                return NotFound();
            }

            return View(upcomingEvent);
        }

        // POST: Admin/UpcomingEvents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var upcomingEvent = await _context.UpcomingEvents.FindAsync(id);
            _context.UpcomingEvents.Remove(upcomingEvent);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UpcomingEventExists(int id)
        {
            return _context.UpcomingEvents.Any(e => e.Id == id);
        }
    }
}

EduHome/Areas/Admin/Views/UpcomingEvents/Create.cshtml
@model EduHome.Models.UpcomingEvent

@{
    ViewData["Title"] = "Create";
}

<h2 style="margin-bottom:20px">Create</h2>

<h4>UpcomingEvent</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Day" class="control-label"></label>
                <input asp-for="Day" class="form-control" />
                <span asp-validation-for="Day" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimeSpan" class="control-label"></label>
                <input asp-for="TimeSpan" class="form-control" />
                <span asp-validation-for="TimeSpan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="TimeDeleted" class="control-label"></label>
                <input asp-for="TimeDeleted" class="form-control" />
                <span asp-validation-for="TimeDeleted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

EduHome/Areas/Admin/Views/UpcomingEvents/Delete.cshtml
@model EduHome.Models.UpcomingEvent

@{
    ViewData["Title"] = "Delete";
}

<h2 style="margin-bottom:20px">Delete</h2>

<h3 class="text-danger" style="margin-bottom:15px">Are you sure you want to delete this?</h3>
<div>
    <h4>UpcomingEvent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Day)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Day)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TimeSpan)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TimeSpan)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TimeDeleted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TimeDeleted)
        </dd>
    </dl>
    
    <form style="margin-top:35px" asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </form>
</div>

EduHome/Areas/Admin/Views/UpcomingEvents/Details.cshtml
@model EduHome.Models.UpcomingEvent

@{
    ViewData["Title"] = "Details";
}

<h2 style="margin-bottom:20px">Details</h2>

<div>
    <h4>UpcomingEvent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Day)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Day)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TimeSpan)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TimeSpan)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TimeDeleted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TimeDeleted)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-secondary" style="margin-top:20px" asp-action="Index">Back to List</a>
</div>

EduHome/Areas/Admin/Views/UpcomingEvents/Edit.cshtml
@model EduHome.Models.UpcomingEvent

@{
    ViewData["Title"] = "Edit";
}

<h2 style="margin-bottom:20px">Edit</h2>

<h4>UpcomingEvent</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Day" class="control-label"></label>
                <input asp-for="Day" class="form-control" />
                <span asp-validation-for="Day" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimeSpan" class="control-label"></label>
                <input asp-for="TimeSpan" class="form-control" />
                <span asp-validation-for="TimeSpan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="TimeDeleted" class="control-label"></label>
                <input asp-for="TimeDeleted" class="form-control" />
                <span asp-validation-for="TimeDeleted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input class="btn btn-primary" type="submit" value="Save" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

EduHome/Areas/Admin/Views/UpcomingEvents/Index.cshtml
@model IEnumerable<EduHome.Models.UpcomingEvent>

@{
    ViewData["Title"] = "Index";
}

<h4 style="margin-bottom:30px">Events</h4>

<p>
    <a class="btn btn-success" style="margin-bottom:20px" asp-controller="UpcomingEvents" asp-action="Create">Create</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Day)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TimeSpan)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsDeleted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TimeDeleted)
            </th>
            <th>
                Settings
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Day)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeSpan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsDeleted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeDeleted)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-secondary"><i class="mdi mdi-information"></i></a>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning"><i class="mdi mdi-update"></i></a> 
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger"><i class="mdi mdi-delete"></i></a>
            </td>
        </tr>
}
    </tbody>
</table>