EduHome/Models/Map.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EduHome.Models
{
    public class Map
    {
        public int Id { get; set; }
        public int Year { get; set; }
        [Required]
        public string EmbedLink { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime? TimeDeleted { get; set; }
    }
}

EduHome/Areas/Admin/Controllers/MapsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EduHome.DAL;
using EduHome.Models;
using EduHome.Extensions;
using Microsoft.AspNetCore.Authorization;

namespace EduHome.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class MapsController : Controller
    {
        private readonly AppDbContext _context;

        public MapsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Admin/Maps
        public async Task<IActionResult> Index()
        {
            return View(await _context.Maps.ToListAsync());
        }

        // GET: Admin/Maps/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var map = await _context.Maps
                .FirstOrDefaultAsync(m => m.Id == id);
            if (map == null)
            {
                return NotFound();
            }

            return View(map);
        }

        // GET: Admin/Maps/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Maps/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Year,EmbedLink,IsDeleted,TimeDeleted")] Map map)
        {
            if (ModelState.IsValid)
            {
                _context.Add(map);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(map);
        }

        // GET: Admin/Maps/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var map = await _context.Maps.FindAsync(id);
            if (map == null)
            {
                return NotFound();
            }
            return View(map);
        }

        // POST: Admin/Maps/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Year,EmbedLink,IsDeleted,TimeDeleted")] Map map)
        {
            if (id != map.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(map);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MapExists(map.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(map);
        }

        // GET: Admin/Maps/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var map = await _context.Maps
                .FirstOrDefaultAsync(m => m.Id == id);
            if (map == null)
            {
                return NotFound();
            }

            return View(map);
        }

        // POST: Admin/Maps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var map = await _context.Maps.FindAsync(id);
            _context.Maps.Remove(map);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MapExists(int id)
        {
            return _context.Maps.Any(e => e.Id == id);
        }
    }
}

EduHome/Areas/Admin/Views/Maps/Create.cshtml
@model EduHome.Models.Map

@{
    ViewData["Title"] = "Create";
}

<h2 style="margin-bottom:20px">Create</h2>

<h4>Map</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmbedLink" class="control-label"></label>
                <input asp-for="EmbedLink" class="form-control" />
                <span asp-validation-for="EmbedLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="TimeDeleted" class="control-label"></label>
                <input asp-for="TimeDeleted" class="form-control" />
                <span asp-validation-for="TimeDeleted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

EduHome/Areas/Admin/Views/Maps/Delete.cshtml
@model EduHome.Models.Map

@{
    ViewData["Title"] = "Delete";
}

<h2 style="margin-bottom:20px">Delete</h2>

<h3 class="text-danger" style="margin-bottom:15px">Are you sure you want to delete this?</h3>
<div>
    <h4>Map</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EmbedLink)
        </dt>
        <dd style="width:450px">
            @Html.DisplayFor(model => model.EmbedLink)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TimeDeleted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TimeDeleted)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </form>
</div>

EduHome/Areas/Admin/Views/Maps/Details.cshtml
@model EduHome.Models.Map

@{
    ViewData["Title"] = "Details";
}

<h2 style="margin-bottom:20px">Details</h2>

<div>
    <h4>Map</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EmbedLink)
        </dt>
        <dd style="width:450px">
            @Html.DisplayFor(model => model.EmbedLink)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsDeleted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsDeleted)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TimeDeleted)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TimeDeleted)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-secondary" style="margin-top:20px" asp-action="Index">Back to List</a>
</div>

EduHome/Areas/Admin/Views/Maps/Edit.cshtml
@model EduHome.Models.Map

@{
    ViewData["Title"] = "Edit";
}

<h2 style="margin-bottom:20px">Edit</h2>

<h4>Map</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmbedLink" class="control-label"></label>
                <input asp-for="EmbedLink" class="form-control" />
                <span asp-validation-for="EmbedLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsDeleted" /> @Html.DisplayNameFor(model => model.IsDeleted)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="TimeDeleted" class="control-label"></label>
                <input asp-for="TimeDeleted" class="form-control" />
                <span asp-validation-for="TimeDeleted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

EduHome/Areas/Admin/Views/Maps/Index.cshtml
@model IEnumerable<EduHome.Models.Map>

@{
    ViewData["Title"] = "Index";
}


<h4 style="margin-bottom:30px">Map</h4>

<p>
    <a class="btn btn-success" style="margin-bottom:30px" asp-controller="Maps" asp-action="Create">Create</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmbedLink)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsDeleted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TimeDeleted)
            </th>
            <th>
                Settings
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Year)
                </td>
                <td style="width:450px !important;">
                    @Html.DisplayFor(modelItem => item.EmbedLink)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsDeleted)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TimeDeleted)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-secondary"><i class="mdi mdi-information"></i></a>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning"><i class="mdi mdi-update"></i></a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger"><i class="mdi mdi-delete"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>